### ISSUE TITLE
Sniffing mode

### ISSUE THREAD

**Issue by FlipB** [ICBTech/nRF905#2]
Nice work.

It would be nice to have a sniffing mode or some way to dump all traffic (even if not matching rx_address) to make it easier to discover your other devices.

**Comment by bandigarf** [comment]
Thanks for your interest in the project and for the idea!

Unfortunately, it is not doable with this hardware.

The nRF905 chip relies on the address bytes in order to distinguish actual data from random noise. Not just this one, pretty much any similar chip which performs packet-based communication.
Upon each tick of the internal clock, the receiver shifts bits into a buffer. When that buffer matches the address bytes, whatever follows is treated as a packet.

If you really want to sniff traffic with such a chip, you would need one that can output the raw clock and demodulated data, and then process the bit-stream on the RPi side.
Or use something even more advanced like RTL-SDR.

**Comment by FlipB** [comment]
Ah, My bad. I skimmed the nrf905 spec and assumed Address Match mode was toggleable, but perhaps it's just for output.
